#ifndef ERROR_H
#define ERROR_H

/* #define ERROR 1
 */
#define SUCCESS 0

/* Command analysis */

#define ERROR_COMMAND_UNKNOW 1  
#define ERROR_COMMAND_NOT_IMPLEMENTED 2
#define ERROR_COMMAND_WITH_WRONG_KEY 3
#define ERROR_WRONG_STATE 4

#define ERROR_VALUE_FIELD_UNKNOW 101

/* AX25 Error */
#define ERROR_AX25_EXCEED_MAX_LENGH 100

/* PROG ERROR */
#define ERROR_PROG_INDEX_NOT_EQUAL 128
#define ERROR_PROG_MEM1_MEM2_NOT_EQUAL 129
#define ERROR_PROG_INDEX_OUT_OF_BOUND 130

/* MAILBOX ERROR */

#define ERROR_MAILBOX_FULL 10
#define ERROR_MAILBOX_NOT_FOUND 11
#define ERROR_MAILBOX_EMPTY 12
#define ERROR_ADD_MSG_EXCED_SIZE 13
#define ERROR_GET_LAST_MSG_CALLSIGN_WRONG_SIZE 14
#define ERROR_MESSAGE_EMPTY 15

#define ERROR_INFO_MSG_INDEX_OUT_OF_BOUND 135
#define ERROR_INFO_MSG_ALREADY_NOT_USED 136

#define ERROR_TLE_WRONG_SIZE 140

#define ERROR_BUFFER_OVERFLOW -10
#define ERROR_WRONG_MODEM_MODE -11
#define ERROR_WRONG_SIZE_RCV -12;

#define ERROR_LOAD_DATA_PAYLOAD_WRONG_SIZE 30

#define   ERROR_CRC  -64

#endif // ERROR_H
